# Generated by Django 4.2.1 on 2023-05-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
