# Generated by Django 4.2.1 on 2023-05-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='indexing',
            field=models.BooleanField(default=True),
        ),
    ]
