# Generated by Django 4.2.1 on 2023-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_remove_blogpost_indexing_alter_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='indexing',
            field=models.CharField(choices=[('index', 'Index'), ('noindex', 'noindex')], default='index', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
